### ISSUE TITLE
Communicate progress of getting/downloading operations

### ISSUE THREAD

**Issue by arthur-shaw** [arthur-shaw/susoapi#37]
# Objective

Communicate progress to the end user for long-running processes.

Two canonical examples:

- Downloading data
- Getting data in chunks

# Tasks

### Research

- [ ] Research progress tools (e.g., [progressr](https://progressr.futureverse.org/index.html))
- [ ] Research console communication tools (e.g., [cli](https://cli.r-lib.org/), [ui_*](https://usethis.r-lib.org/reference/ui.html) functions in usethis)

### Refactor

- [ ] For download functions, provide % downloaded
- [ ] For getting functions, provide % of all records gotten

# Related issues

**Comment by arthur-shaw** [comment]
This would be useful in a few areas:

- Shiny apps that report % progress to users
- Console updates

This is priority due to the number of projects that would benefit from this.
