### ISSUE TITLE
Add badges to package

### ISSUE THREAD

**Issue by arthur-shaw** [arthur-shaw/susoapi#38]
# Objective

Inform users how mature the package and its individual functions are, respectively.

# Tasks

- [ ] Add code coverage badge for test coverage
- [ ] Add CRAN badge so clear not on CRAN
- [ ] Add experimental lifecycle badges to new/experimental functions
